### ISSUE TITLE
Dead code? 

### ISSUE THREAD

**Issue by cjcjameson** [cloudfoundry/guardian#102]
We were looking for example usages of the `gosigar` library, and came across https://github.com/cloudfoundry/guardian/blob/master/sysinfo/resources_provider.go

However, this looks like dead code in this repo. Ya?

**Comment by emalm** [comment]
@cjcjameson Why do you think it's dead? Seems to be used at https://github.com/cloudfoundry/guardian/blob/master/guardiancmd/command.go#L417.

**Comment by cjcjameson** [comment]
Darn, yep: https://github.com/cloudfoundry/guardian/blob/8cd3aeee278245e0423c9a9262b15a3270fea04b/guardiancmd/command.go#L418

IDE must not have been showing us the reference. Good to see, so thanks for pointing it out!
