### ISSUE TITLE
Feasibility of net_cls cgroups and classids for Processes

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/guardian#111]
## Background
As part of a larger effort around using sidecar proxies inside of containers, we are exploring various mechanisms for redirecting app traffic to a sidecar Envoy proxy.

In **one scenario we're considering**, we'd avoid acting on packets originating from the Envoy itself, while simultaneously modifying all other packets in the container.  Since both the Envoy and the app are in the same container (hence same network namespace), we'd need some way to distinguish between the originating processes.

One approach that we've explored was to [use the `net_cls` cgroup](https://www.kernel.org/doc/Documentation/cgroup-v1/net_cls.txt).  This [seems to work for us](https://www.pivotaltracker.com/story/show/156902302/comments/188564439).

The requirements are:
1. Different processes in the container belong to different `net_cls` cgroups
2. Those cgroups have different values in their `net_cls.classid` file

With those pieces in place, we (as the networking plugin) could install iptables rules which match or don't match on the different `classid` values.

The next step in exploring feasibility for Cloud Foundry would be to understand how we could do this in Garden.

## Imaginary implementation

So, just to pull a possible implementation out of thin air, perhaps the `ProcessSpec` gets a new field `NetClassID`.  If that is nonzero, then guardian might:
- create a sub-cgroup of the container's cgroup, perhaps named using that `classid`
- write the value of the `NetClassID` to the `net_cls.classid` file in the cgroup
- move the process into the cgroup

## The Questions
We may not need to do this at all, so we don't want to get too deep right now.  But in order to help us weigh possible options, a superficial smell-test would be helpful:

**Does this sound feasible in Garden & Guardian?**

cc @christianang

**Comment by julz** [comment]
Don't see why that wouldn't work from a garden perspective: we already create a per-Process cgroup for sidecar containers when you opt-in to setting sidecar-specific cpu/mem limits, this seems like it'd extend reasonably naturally from that. I haven't given any thought to the security of that wrt networking/iptables 'cos you'd know that more than me.

Initial sniff test result: linen in breeze
