### ISSUE TITLE
Guardian should not report a container's age if configured with a runtime plugin that does not report a created time

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/guardian#126]
## Description

The `Created` time field `runc` outputs as part of it's container `state` is not part of the [runtime spec](https://github.com/opencontainers/runtime-spec/blob/a1b50f621a48ad13f8f696a162f684a241307db0/specs-go/state.go#L4-L17). If `guardian` is run with a runtime plugin that does not output this (e.g. `winc`), then the `Age` field calculated by `guardian` is very incorrect and also does not change as the container ages, as it is the max `int64` value possible.

## Steps to reproduce

- Start `guardian` with a runtime plugin that does not report the `Created` time for a container (e.g. `winc`)
- Create a container
- Get the metrics for that container
- See the container `Age` is `9223372036854775807` (max `int64`)

## Suggested Fix
Instead of just taking the unmarshaled value from the runtime plugin output [here](https://github.com/cloudfoundry/guardian/blob/44208d0ca9591870166e0ed7db4e89b5f5d8336d/rundmc/runrunc/stats.go#L76) be defensive and do a check if the `time.Time` value is zero. If it is, just do not report an `Age` since we cannot get it correct.
- see: https://github.com/cloudfoundry/guardian/pull/127

**Comment by Callisto13** [comment]
Closing as fixed in next version of GRR 1.19.2
