### ISSUE TITLE
Running a container with a custom `USER name:group` fails

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/guardian#151]
## Todos

Please try the following before submitting the issue:

- [N/A] Upgrade Concourse if you are observing a failure in a test
- [X] Use latest BOSH stemcell if the problem occurred in a BOSH VM
- [N/A] Use Go 1.6 if the issue has to do with running unit tests locally

## Description

Trying to run a docker container on CF that uses `USER user:group` in the Dockerfile. I am getting a message saying the group doesn’t exist, but it appears like it should exist in the image.

```
2019-10-07T11:12:18.13-0400 [API/6] OUT App instance exited with guid 09fec994-0f43-4716-883d-567e90523854 payload: {"instance"=>"e19bf5a2-3330-4f6c-59c6-7978", "index"=>0, "cell_id"=>"9e3ead9f-4791-40b4-a35d-3d0b52c5bd95", "reason"=>"CRASHED", "exit_description"=>"unable to find group vcap: no matching entries in group file", "crash_count"=>1, "crash_timestamp"=>1570461138069089483, "version"=>"a311ef4d-8a27-4a9a-978a-ec3c499bbe8e"}
```

The group appears to exist though:

```
$ docker pull dmikusa2pivotal/diego-app
$ docker run -it dmikusa2pivotal/diego-app grep 'vcap' /etc/group
vcap:x:1000:
```

I've left the image up on Docker Hub so feel free to take a look at it. It's created using https://github.com/cloudfoundry/diego-dockerfiles/blob/master/diego-docker-app/Dockerfile and my custom Dockerfile.

```
FROM cloudfoundry/diego-docker-app
USER vcap:vcap
```

This message seems to come through from runc here -> https://github.com/cloudfoundry/guardian/blob/master/rundmc/users/lookup_linux.go

## Logging and/or test output

See above.

## Steps to reproduce

```
cf push -o dmikusa2pivotal/diego-app diego-app
```

For what it's worth, [this line](https://github.com/cloudfoundry/guardian/blob/master/rundmc/users/lookup_linux.go#L23) is passing through a blank string instead of the path to `/etc/group`. It seems like that causes runc to be unable to resolve `vcap` into the group id.

If I put `USER 1000:1000` that bypasses the issue and I can run my container.

Ex:

```
cf push -o dmikusa2pivotal/diego-app-id diego-app-id
```

**Comment by julz** [comment]
This should be fixed in [v1.19.9](https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.19.9), thanks for the report!
