### ISSUE TITLE
Weird properties-path behavior

### ISSUE THREAD

**Issue by kallisti5** [cloudfoundry/guardian#158]
There is some weird behavior around --properties-path:

  * If the file provided for --properties-path doesn't exist, garden runs as expected.
  * If the file provided for --properties-path is a blank file, garden doesn't start (json parsing failure)

It feels like garden needs to do a size check on accepted json configuration files before attempting to parse them as json to help avoid failures?  Help ensure blank == doesn't exist.

**Comment by julz** [comment]
Hi @kallisti5 - this should be fixed now (see 
https://www.pivotaltracker.com/story/show/169999586), thanks!
