### ISSUE TITLE
Support for pre-3.19 kernels?

### ISSUE THREAD

**Issue by vito** [cloudfoundry/guardian#29]
As far as I know the only thing requiring 3.19 is the use of the `execveat` syscall used by `nstar.c` for `StreamIn`/`StreamOut`. Unfortunately the use of 3.19+ is not yet widespread: lots of infrequently-updated-but-commonly-required distributions are still a ways behind. For example, CentOS 7.2 is on 3.10, without a blessed way to upgrade.

Is there an alternative approach to solving the security issue that `execveat` was used to fix? Or, if the syscall is not present, could we (/ should we) fall back on the less-secure-but-working code path?

The answer to these questions may be no, just wanted to raise this as an issue that affects Concourse/Guardian adoption.

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#118145633](https://www.pivotaltracker.com/story/show/118145633) Support for pre-3.19 kernels?


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by goonzoid** [comment]
We could probably fix this by porting nstar to Go, which we've talked about doing anyway. We have a story for that in the icebox, I'll pull it into the backlog.

**Comment by julz** [comment]
closing for now - we have no current plans to support older kernels, though we'd be very happy to accept PRs that added support

**Comment by Murryy79** [comment]
I ran into this "could not read file "metadata.json from tar" issue today 
we have a few pipelines working for few months. 
just ran into this issue with a new pipeline
how do i check my kernel version? on which host?

**Comment by julz** [comment]
Hi @Murryy79 you can check your kernel version by running `uname -r` on the host where the worker is running
