### ISSUE TITLE
seems outdated replace directive in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [cloudfoundry/guardian#341]
Module `code.cloudfoundry.org/guardian` at now indirectly depends on `v0.6.0` of `golang.org/x/text`.
Version of `golang.org/x/text` before `v0.3.8` suffers vulnerability([GO-2022-1059](https://pkg.go.dev/vuln/GO-2022-1059)) but there is a replace line in your go.mod to pin `golang.org/x/text` to `v0.3.7`. Should it be dropped or reserved for some special reason?<br>
<https://github.com/cloudfoundry/guardian/blob/main/go.mod#L106>
```txt
replace (
    ...
    golang.org/x/text => golang.org/x/text v0.3.7
)
```

**Comment by winkingturtle-vmw** [comment]
@Morty-luo I am not sure why that replace directive is there. Thanks for bringing that to our attention. It's now been removed.
