### ISSUE TITLE
/dev/null file descriptor leak

### ISSUE THREAD

**Issue by vito** [cloudfoundry/guardian#35]
All 3 workers behind our Concourse pipeline for a duration of ~2 days eventually started hitting an open fd limit.

This resulted in a string of interesting errors: https://ci.concourse.ci/builds?since=135962 - some of which may be due to missing err checks beforehand (some complain that a file just doesn't exist, but the file probably actually failed to be created and Guardian didn't short-circuit)

The `lsof -p` of each worker is here: https://gist.github.com/vito/21a2a4ac9678b227a0cb37d7bb54f0f3

Looks like all of the leaked fds are `/dev/null`.

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#119644893](https://www.pivotaltracker.com/story/show/119644893) /dev/null file descriptor leak


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by julz** [comment]
This should be fixed due to iodaemon no longer existing(!). Thanks!
