### ISSUE TITLE
Enhancement: add -m comment --comment ${container-handle} to iptables rules

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/guardian#37]
Since the instance IDs used in iptables rules no longer match the names of directories in the container depot, it would be really cool if the the rules themselves pointed to the container handle to make it easier to associate rule with the container.

A comment can be up to 256 characters long and, IIRC, that's longer than the maximum supported length of a container handle.

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#121026363](https://www.pivotaltracker.com/story/show/121026363) Enhancement: add -m comment --comment ${container-handle} to iptables rules


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by julz** [comment]
Woah. Yes, I love this idea.

**Comment by julz** [comment]
Implemented in db50aa60. Thanks @sykesm!
