### ISSUE TITLE
CAP_AUDIT_READ runc error

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/guardian#38]
When using concourse which uses cf guardian which uses runc (holy cow), I get this cryptic error:

`runc start: exit status 1: unknown capability "CAP_AUDIT_READ"`

I'm running on the standard AWS EC2 Ubuntu 14.04 LTS HVM AMI (what a word-full).

It seems as though this kernel does not have `CAP_AUDIT_READ`. It DOES have the following:

```
ubuntu@ip-172-31-18-217:~$ man capabilities | grep CAP_AUDIT -a2
       CAP_AUDIT_CONTROL (since Linux 2.6.11)
              Enable  and  disable  kernel auditing; change auditing filter rules; retrieve auditing
              status and filtering rules.

       CAP_AUDIT_WRITE (since Linux 2.6.11)
              Write records to kernel auditing log.
```

This effectively makes concourse on AWS dead in the water for me, since [guardian only supports Ubuntu 14.04 LTS](https://github.com/cloudfoundry-incubator/garden-runc-release/blame/master/README.md#L47) and this bug/whatever prevents me from running it on the Ubuntu 14.04 LTS AMI.

**Comment by jadekler** [comment]
Related: https://www.pivotaltracker.com/n/projects/1158420/stories/119257379

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#121887295](https://www.pivotaltracker.com/story/show/121887295) CAP_AUDIT_READ runc error


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by DenisIzmaylov** [comment]
I got the same issue on Ubuntu 14.04.4 LTS

**Comment by DenisIzmaylov** [comment]
Good discussion here:
https://github.com/opencontainers/runc/issues/924

**Comment by DenisIzmaylov** [comment]
![image](https://cloud.githubusercontent.com/assets/1690596/16400342/0af82da4-3ce3-11e6-9528-c19bc31c8e9d.png)

It's just clean installation of Ubuntu 14.04.4 LTS with Concourse running in docker compose:

+ https://github.com/MeteoGroup/concourse-ci

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by DenisIzmaylov** [comment]
It seems you've kernel version is less than 3.19. You can check it:
```bash
$ uname -r
3.13.0-88-generic
```
The example below means you have kernel version 3.13 while Concourse (and guardian) requires a 3.19+ kernel. It means you have to update the kernel.

For me [it was](https://wiki.ubuntu.com/Kernel/LTSEnablementStack#Server):
```bash
sudo apt-get install --install-recommends linux-generic-lts-wily 
```

Then I reboot the server and now everything is working. You can read full discussion [here](https://github.com/opencontainers/runc/issues/924#issuecomment-229207866). Have a good update! :)

**Comment by DenisIzmaylov** [comment]
Let's close it?

**Comment by jamesread** [comment]
This breaks compatibility with RHEL6, RHEL7, and it's it's derivatives - Oracle Linux, Scientific Linux, CentOS, because they use older kernels that don't have this CAP. RHEL6 is 2.6.32 based, RHEL7 is 3.10 based.

**Comment by DenisIzmaylov** [comment]
Yes, it would be great to add OS which already has compatible kernels and recommend for everyone who have older versions just to update kernel.

**Comment by julz** [comment]
Hi @jadekler & @DenisIzmaylov - glad you have a workaround for now! We do have a story to support this linked in the second comment so I'll keep this issue open but just to avoid getting anyone's hopes up, concourse relies on another guardian feature that requires 3.19+ (specifically the StreamIn feature which requires the execveat system call) so at least until we find a way to not need that, 3.19 will stay a hard requirement.

**Comment by jamesread** [comment]
I just tried Debian 8 too, which is also the current stable and it's got a 3.16 kernel. 

Ack that 3.19 is a requirement, but it seems Guardian (and hence Concourse etc) will only run on Ubuntu out of the major Linux Distros. 

Could a workaround for StreamIn/execveat be found?

**Comment by julz** [comment]
Hi @jamesread - ack that it'd be nice to support a broader range of OSes that are on older kernels.. if someone PRed a version of StreamIn that didn't require `execveat` and was secure we'd totally look at that, however my recollection is we need the `execveat` (as opposed to `execve`) to be secure against symlink traversals in the container potentially leading to container breakout, so I'd hesitate to accept a change unless we were confident of the security implications

**Comment by donaldguy** [comment]
For what its worth, I've been running on stock 16.04 with only intermittent issues - depending on how frequently you turn over workers in a spot fleet or similar, it might be just as good as dealing with curating a psuedo-stemcell for 14.04.

**Comment by julz** [comment]
closing - we have no current plans to support older kernels, though as above we're happy to accept PRs that add support

**Comment by predatorian3** [comment]
@jamesread I've had luck with Oracle Linux 7 running Docker then running the Concourse-CI Containers provided. I have yet to try in a distributed setup rather than a single server, and I was able to get those working on my local machine (MacOS 10.12.6)

Maybe running the binary on its own isn't the right answer in this case.
