### ISSUE TITLE
Hangs when attaching to processes (possibly already-exited ones)

### ISSUE THREAD

**Issue by vito** [cloudfoundry/guardian#41]
## Description

Had a Concourse deploy that rolled the workers (not stemcell). When they came back, re-attaching to processes would hang. I'm not sure whether these processes had exited while Garden was down.

## Logging and/or test output

Here's a stack dump: https://gist.githubusercontent.com/vito/508c434965b3d5c16ca337102a9cb37e/raw/cdc39744c647640ee6fca998eaa30b940cd9dc4c/hanging-gardens

Running it through [Swirly](https://rawgit.com/vito/swirly/master/index.html), the following sticks out:

![screenshot from 2016-08-06 19-51-04](https://cloud.githubusercontent.com/assets/1880/17460180/267b4d2c-5c0f-11e6-8fac-7b8e5295dc99.png)

These seem to correlate to the hanging builds. They were stuck for >1h before I noticed (the >80 mins ones), and then I tried aborting one of the stick builds and bounced the ATCs and observed it happen again (the ~10min one).

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#127858315](https://www.pivotaltracker.com/story/show/127858315) Hangs when attaching to processes (possibly already-exited ones)


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by garden-gnome** [comment]
Hello again!

All stories related to this issue have been accepted, so I'm going to automatically close this issue.

At the time of writing, the following stories have been accepted:

* [#127869117](https://www.pivotaltracker.com/story/show/127869117) As a user I can re-attach to a process that died while garden was stopped and get its exit code


If you feel there is still more to be done, or if you have any questions, leave a comment and we'll reopen if necessary!
