### ISSUE TITLE
Auto-detect MTU?

### ISSUE THREAD

**Issue by vito** [cloudfoundry/guardian#46]
GCE machines have an MTU of 1460. Guardian/Garden-runC default to 1500, so network packets in containers would randomly be dropped, causing things to hang.

Is there any way this could be auto-detected and remove the 1500 default?

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#128237753](https://www.pivotaltracker.com/story/show/128237753) Auto-detect MTU?


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by vito** [comment]
Nevermind. See https://github.com/docker/docker/issues/22028
