### ISSUE TITLE
docker 1.9 'dind' support

### ISSUE THREAD

**Issue by SillyMoo** [cloudfoundry/guardian#52]
## Description

I have some systems still requiring images in the docker 1.9 image format (there was a breaking change between 1.9 and 1.10). So I modified the docker-resource-image repo to use docker 1.9 instead of docker 1.12. Things work ok until you try do a docker build and then the failure below occurs
## Logging and/or test output

I get the following error when using docker 1.9:

[8] System error: write /sys/fs/cgroup/devices/0c1e319c-49fe-4383-7e87-fd53d98c8890/docker/72d46daae1df3a409aae40009b4849273fd1e9a91971a737404f1d4122f8ce4c/devices.allow: operation not permitted
## Steps to reproduce

Using concourse-ci 2.0.2 run up a dind container which containers docker 1.9 (example here: https://github.com/SillyMoo/docker-image-resource/tree/1.9). Calls to docker build will fail with cgroup errors not present with docker 1.12.

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#130041077](https://www.pivotaltracker.com/story/show/130041077) docker 1.9 'dind' support


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by julz** [comment]
This seems like a docker in docker problem, not a garden problem. Since docker 1.10 works fine (if I understand correctly) garden is clearly allowing sub-containers to work properly. Do you have an idea of what change you would like us to make to fix this?

**Comment by SillyMoo** [comment]
To be honest I don't really know how your runc stuff in garden works, so I can't suggest a fix. I'll check whether dind of docker 1.9 works in 1.10, to confirm if it's a docker issue.
