### ISSUE TITLE
GPU instances

### ISSUE THREAD

**Issue by drahnr** [cloudfoundry/guardian#71]
Is it possible to map (nvidia or AMD) GPUs into the container using guardian/garden? If so, where can I find more information?

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#141485301](https://www.pivotaltracker.com/story/show/141485301) GPU instances


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by julz** [comment]
Hi @drahnr - it's not currently possible, but we've heard this request from a few people and are interested in the idea. We plan to investigate adding this but/and would welcome PRs in the meantime. Thanks!

**Comment by drahnr** [comment]
The biggest thing is to map 

    [nvidia] /dev/{nvidia0,nvidiactl,nvidia-modeset,nvidia-uvm,nvidia-uvm-tools}
    [amd] /dev/kfd

device nodes into the OCI container.

**Comment by mkocher** [comment]
@drahnr I only have a passing familiarity with using GPUs on servers. How does that work with multiple containers trying to use the GPU? How would it work with  multiple tenants on the same CF using Garden?

**Comment by drahnr** [comment]
All GPUs/GPU-drivers have schedulers. The biggest issue is VRAM which might run out and crash applications.
But this is really a problem of the layers stacked on top of garden (in my case, concourse, which should model that). It is a shared resource after all.
If one wanted to implement it in garden, I would go with a concept of GPU ownership/token passing per GPU.

**Comment by svrc-pivotal** [comment]
I exposed the NVIDIA devices by flag with this branch here a few months ago: https://github.com/svrc-pivotal/guardian/tree/nvidia

This doesn't do scheduling yet however so you would need to use placement tags and isolation segments.  I have a NVIDIA cuda driver bosh addon nearly completed to run this for real.  A prototype of including GPUs as a Diego scheduled resource is something I have half baked for a month which I should dust off...

**Comment by drahnr** [comment]
Do you have link to the Diego part?

**Comment by mogul** [comment]
Hey there, did this work move forward after this discussion?

**Comment by mogul** [comment]
Per @julz in Slack:
> it’s not something we ended up prioritising unfortunately; afaik no updates since the [issue comment here]

**Comment by giner** [comment]
I'm wondering if Eirini could make it possible.
