### ISSUE TITLE
Configuring container's DNS search domains

### ISSUE THREAD

**Issue by pn-santos** [cloudfoundry/guardian#73]
I've been using concourse and I've ran into a issue with it's container's DNS config, I need to configure a search domain in order to be able to use just the hostname and not the FQDN of certain hosts.

Currently I can configure the DNS servers via the `CONCOURSE_GARDEN_DNS_SERVER` however there seems to be no way to configure DNS search domains. Is there a way one can configure the search domains of containers?

I'm running concourse with docker, and tried using the `dns-search` argument when running the worker container however that seems to have no effect on the containers the worker creates.

Potentially useful info:
- Linux 4.8.0-46-generic
- Docker 1.13.0
- Concourse 2.7.3

**Comment by julz** [comment]
Hi @pn-santos - unfortunately as of right now we don't support explicitly configuring search domains for the container when dns servers are explicitly specified via `--dns-server`. We _do_ support maintaining any extra information in the host's resolv.conf when DNS is configured implicitly by copying that in to the container (this is the way resolv.conf is configured if explicit DNS isn't provided). If this fits your needs that may be a solution. Alternatively you might consider (as a workaround) writing resolv.conf yourself as root within the container, which should be allowed.
