### ISSUE TITLE
Concourse 2.7.3 mounts /etc/hosts as UID 65534

### ISSUE THREAD

**Issue by hfinucane** [cloudfoundry/guardian#74]
# Bug Report

`/etc/hosts`, for all its faults, is a great way to have non-global DNS for smoke tests. Between Concourse 2.7.0 and 2.7.3, it looks like a change was made that bind mounts it into containers as UID 65534, AKA nobody, AKA nfsnobody, depending on who you ask. This breaks the ability of Concourse tasks to use /etc/hosts as a quick and easy split-horizon DNS.

**Comment by hfinucane** [comment]
Duplicated [from the Concourse bug tracker](https://github.com/concourse/concourse/issues/1021) on [this advice](https://concourseci.slack.com/archives/C07RY25QF/p1492635672225080)

**Comment by craigfurman** [comment]
@julz Our tracker integration closed this automatically, and is somehow able to masquerade as real people like me. Not sure if this should be closed before you accept the story, should we reopen?
