### ISSUE TITLE
Dead Run/Attach consumers stick around and siphon process output into the abyss

### ISSUE THREAD

**Issue by vito** [cloudfoundry/guardian#75]
## Description

Concourse's ATCs can go away and reattach to builds that were in flight. However, Garden seems to retain some state from the original attaching of the process (via both `Run` or `Attach`), resulting in the re-attaching losing 50% of the output, resulting in very odd looking build logs. For example:

https://ci.concourse.ci/teams/main/pipelines/main/jobs/topgun/builds/330

All we need is to not have this permanent output loss; we're OK with losing a window of log output during the detach + reattach, we just don't want build logs to be butchered after reattaching. [`http.CloseNotifier`](https://golang.org/pkg/net/http/#CloseNotifier) may be of use here - we use it in Concourse for closing event streams for dead clients, and it seems pretty straightforward.

## Logging and/or test output

(n/a)

## Steps to reproduce

* Spawn a long-running process printing monotonically increasing numbers (`1, 2, 3, 4, 5, 6, ...`).
* Kill the thing that spawned and attached to the process.
* Run another thing that attaches to the process.
* You will see something like `10, 12, 14, 16, ...`. Ideally you'd see something like `10, 11, 12, 13, 14, ...`.

**Comment by teddyking** [comment]
This has been done, shipped in [garden-runc-release v1.9.0](https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.9.0). Thanks!
