### ISSUE TITLE
iptables FORWARD chain DROP policy breaks workers

### ISSUE THREAD

**Issue by pn-santos** [cloudfoundry/guardian#78]
Re-opening [this issue](https://github.com/concourse/concourse/issues/897) here as it seems this regards guardian.

I've come across the issue in machines (where workers are installed in) that have a default DROP policy for the FORWARD and INPUT chain and the last rule of the chain is a REJECT. 

When starting the worker the  `w--forward` rule is added at the end of the FORWARD chain, which means that packets will be dropped before they reach the that rule. However even if the `w--forward` rule is moved up, any NEW connections will be dropped (since the `w--default` rule doesn't pick up packets with ctstate NEW)

Initial INPUT and FORWARD chains:
```
Chain INPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    (...)
    0     0 LOG        all  --  *      *       0.0.0.0/0            0.0.0.0/0            limit: avg 5/min burst 5 LOG flags 0 level 7 prefix "iptables INPUT denied: "
    0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 LOG        all  --  *      *       0.0.0.0/0            0.0.0.0/0            limit: avg 5/min burst 5 LOG flags 0 level 7 prefix "iptables FORWARD denied: "
    0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable
```

After the concourse worker is started:
```
Chain INPUT (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    (...)
    0     0 LOG        all  --  *      *       0.0.0.0/0            0.0.0.0/0            limit: avg 5/min burst 5 LOG flags 0 level 7 prefix "iptables INPUT denied: "
    0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 w--input   all  --  w+     *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 LOG        all  --  *      *       0.0.0.0/0            0.0.0.0/0            limit: avg 5/min burst 5 LOG flags 0 level 7 prefix "iptables FORWARD denied: "
    0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 w--forward  all  --  w+     *       0.0.0.0/0            0.0.0.0/0

Chain w--default (0 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED

Chain w--forward (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  eth1   *       0.0.0.0/0            0.0.0.0/0
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain w--input (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  eth1   *       0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```
After moving the `w--forward` and `w--input` rule up and trying to run a job it's easy to see that requests are being blocked
```
Apr 21 10:01:14 n0 kernel: iptables FORWARD denied: IN=wbrdg-c0a80000 OUT=eth1 MAC=66:b8:b0:60:92:a4:82:52:67:81:a5:88:08:00 SRC=192.168.0.2 DST=10.34.104.11 LEN=66 TOS=0x00 PREC=0x00 TTL=63 ID=58362 DF PROTO=UDP SPT=38584 DPT=53 LEN=46
```
So my first question is shouldn't the `w--default` rule be `ctstate NEW,RELATED,ESTABLISHED` ?
This will not completely solve the problem though since inbound forwarding is also blocked (after adding `ctstate NEW` to the `w--default` rule)
```
Apr 21 10:08:48 n0 kernel: iptables FORWARD denied: IN=eth1 OUT=wbrdg-c0a80004 MAC=00:0c:29:42:14:01:00:10:db:ff:10:00:08:00 SRC=10.34.104.11 DST=192.168.0.6 LEN=150 TOS=0x00 PREC=0x00 TTL=62 ID=39046 PROTO=UDP SPT=53 DPT=38440 LEN=130
```

As far as I can tell the following config solves the forwarding problem but I'm not a iptables expert so not really sure if it makes sense or is the right solution.
```
Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
  884 66730 w--forward  all  --  w+     *       0.0.0.0/0            0.0.0.0/0
 1512 2063K w--forward  all  --  *      w+      0.0.0.0/0            0.0.0.0/0
    0     0 LOG        all  --  *      *       0.0.0.0/0            0.0.0.0/0            limit: avg 5/min burst 5 LOG flags 0 level 7 prefix "iptables FORWARD denied: "
    0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable

Chain w--default (7 references)
 pkts bytes target     prot opt in     out     source               destination
  884 66730 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate NEW,RELATED,ESTABLISHED

Chain w--forward (2 references)
 pkts bytes target     prot opt in     out     source               destination
 1512 2063K ACCEPT     all  --  eth1   *       0.0.0.0/0            0.0.0.0/0
    (... forwarding rules for each container instance ...)
```

So in summary:

1. With a default DROP FORWARD policy, concourse generated rules are not sufficient to enable traffic forwarding between host and containers
2. If the last rule of the INPUT/FORWARD is a REJECT, concourse generated rules will never be reached.

Not sure if something can be done about the second issue but the first one definitely seems to be a problem.

- concourse 2.7.3 (binary release)
- Linux 4.9.0
- iptables v1.4.21

**Comment by julz** [comment]
Hi @pn-santos - I guess my question is whether it makes sense for garden to overrule your iptables configuration if you have it set to drop FORWARD packets. Is there a reason you need to have your iptables configuration set up this way or could you change this setting yourself before starting garden?

**Comment by pn-santos** [comment]
Well the DROP Forward default policy is part of the security rules where I work so I can't really change that. I can however setup forward rules if need be. As I described in the above post, my first reaction was just to move the garden created rules above the default reject, however that didn't work.
I guess my question is then, what should be the config that should be in place in terms of input and forwarding for garden to work assuming that the default forward will be a reject policy?

**Comment by julz** [comment]
Hi @pn-santos, this isn't a use case garden currently supports but we'd be happy to accept a pull request to add support for this as long as it doesn't break the current behaviour (which it doesn't seem like it should) and as long as we can be convinced there are no new security holes this would introduce. Since we're a small team we won't have resources to work on this ourselves very soon so I'll close this issue for now, but again we'd be very happy to accept contributions (and to help out in #garden slack channel).
